language: node_js
node_js:
  - 12
addons:
  chrome: stable

cache:
  yarn: true
env:
  global:
    - NODE_ENV='test'
    - API_URL='https://cake-api.faxity.se'

before_install:
  - yarn global add forever

before_script:
  - wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/build/iFaxity/jsramverk
script:
  - forever start -c 'yarn serve' ./
  - yarn run test
after_script:
  - forever stopall
